-- -----------------------------------------------------
-- Euro. Revisado el 5-12-2001. Lucas Fernández Pérez 
-- No se han realizado cambios.
-- -----------------------------------------------------
CREATE OR REPLACE PROCEDURE DELETE_FRAC_VOL
		(xFRAC 	IN INTEGER,
		 xIdValor 	IN integer)
AS
  xESTA CHAR(7);
BEGIN

	SELECT ESTADO INTO xESTA FROM FRACCIONAMIENTO_VOL WHERE ID=xFRAC;


	/* BORRAR LA LISTA DE INGRESOS */
	DELETE FROM INGRESOS_FRAC_VOL WHERE FRAC=xFRAC;

	/* BORRAR EL SEÑALAMIENTO DE PLAZOS */
	DELETE FROM PLAZOS_FRAC_VOL WHERE FRACCIONA=xFRAC;

	/* BORRAR LA CABECERA DEL FRACCIONAMIENTO */
	DELETE FROM FRACCIONAMIENTO_VOL WHERE ID=xFRAC;

	IF (xESTA<>'CERRADO') THEN
		UPDATE VALORES SET IS_LIVE='S', 
				F_SUSPENSION=NULL, 
				DEMORA_PENDIENTE=0
		WHERE ID=xIDValor
				AND F_INGRESO IS NULL
				AND FECHA_DE_BAJA IS NULL
				AND IS_LIVE='N';
	END IF;

END;
/

