--cuando se modifique id_xxx, modificar bitacoras con registros de tipo E/S y modalidad EM de embargo

caja quitar


ALTER TABLE EXPEDIENTES ADD EMBARGO_1 CHAR(1) DEFAULT '0'
ALTER TABLE EXPEDIENTES ADD EMBARGO_3 CHAR(1) DEFAULT '0'
ALTER TABLE EXPEDIENTES ADD EMBARGO_4 CHAR(1) DEFAULT '0'
ALTER TABLE EXPEDIENTES ADD EMBARGO_8 CHAR(1) DEFAULT '0' 
ALTER TABLE EXPEDIENTES ADD EMBARGO_X CHAR(1) DEFAULT '0'
UPDATE EXPEDIENTES SET EMBARGO_1=ESTA_EMBARGO WHERE EMBARGO='1'
UPDATE EXPEDIENTES SET EMBARGO_3=ESTA_EMBARGO WHERE EMBARGO='3'
UPDATE EXPEDIENTES SET EMBARGO_4=ESTA_EMBARGO WHERE EMBARGO='4'
UPDATE EXPEDIENTES SET EMBARGO_8=ESTA_EMBARGO WHERE EMBARGO='8'
UPDATE EXPEDIENTES SET EMBARGO_X=ESTA_EMBARGO WHERE EMBARGO='X'

ALTER TABLE EXPEDIENTES ADD FECHA_DILI_CUENTAS DATE
ALTER TABLE EXPEDIENTES ADD F_EMBARGO_CUENTAS DATE
ALTER TABLE EXPEDIENTES ADD FECHA_DILI_SALARIOS DATE
ALTER TABLE EXPEDIENTES ADD F_EMBARGO_SALARIOS DATE
ALTER TABLE EXPEDIENTES ADD FECHA_DILI_inmuebles DATE
ALTER TABLE EXPEDIENTES ADD F_EMBARGO_INMUEBLES DATE
ALTER TABLE EXPEDIENTES ADD FECHA_DILI_VEHICULOS DATE
ALTER TABLE EXPEDIENTES ADD F_EMBARGO_VEHICULOS DATE
ALTER TABLE EXPEDIENTES ADD F_EMBARGO_OTROS DATE
UPDATE EXPEDIENTES SET FECHA_DILI_CUENTAS=FECHA_DILIGENCIA WHERE EMBARGO='1'
UPDATE EXPEDIENTES SET F_EMBARGO_CUENTAS=F_EMBARGO WHERE EMBARGO='1'
UPDATE EXPEDIENTES SET FECHA_DILI_SALARIOS=FECHA_DILIGENCIA WHERE EMBARGO='3'
UPDATE EXPEDIENTES SET F_EMBARGO_SALARIOS=F_EMBARGO WHERE EMBARGO='3'
UPDATE EXPEDIENTES SET FECHA_DILI_INMUEBLES=FECHA_DILIGENCIA WHERE EMBARGO='4'
UPDATE EXPEDIENTES SET F_EMBARGO_INMUEBLES=F_EMBARGO WHERE EMBARGO='4'
UPDATE EXPEDIENTES SET FECHA_DILI_VEHICULOS=FECHA_DILIGENCIA WHERE EMBARGO='8'
UPDATE EXPEDIENTES SET F_EMBARGO_VEHICULOS=F_EMBARGO WHERE EMBARGO='8'
UPDATE EXPEDIENTES SET F_EMBARGO_OTROS=F_EMBARGO WHERE EMBARGO='X'

ALTER TABLE EXPEDIENTES ADD E_LOTE3 CHAR(1) DEFAULT 'N' check (E_LOTE3 in ('N','P','R','S'))
ALTER TABLE EXPEDIENTES ADD LOTE_3 CHAR(8) 
ALTER TABLE EXPEDIENTES ADD LOTE_4 CHAR(8) 
ALTER TABLE EXPEDIENTES ADD LOTE_8 CHAR(8) 
UPDATE EXPEDIENTES SET E_LOTE3=E_LOTE
UPDATE EXPEDIENTES SET LOTE_3=LOTE WHERE EMBARGO='3'
UPDATE EXPEDIENTES SET LOTE_4=LOTE WHERE EMBARGO='4'
UPDATE EXPEDIENTES SET LOTE_8=LOTE WHERE EMBARGO='8'

ALTER TABLE EXPEDIENTES DROP COLUMN E_LOTE
ALTER TABLE EXPEDIENTES DROP COLUMN LOTE

ALTER TABLE VALORES ADD ID_SALARIOS      INTEGER
ALTER TABLE VALORES ADD ID_VEHICULOS     INTEGER
ALTER TABLE VALORES ADD ID_OTROSTRAMITES INTEGER
UPDATE VALORES V SET ID_SALARIOS=ID_INMUEBLES 
	WHERE EXPEDIENTE IN (SELECT ID FROM EXPEDIENTES WHERE ID=V.EXPEDIENTE AND EMBARGO='3')
UPDATE VALORES V SET ID_VEHICULOS=ID_INMUEBLES 
	WHERE EXPEDIENTE IN (SELECT ID FROM EXPEDIENTES WHERE ID=V.EXPEDIENTE AND EMBARGO='8')
UPDATE VALORES V SET ID_OTROSTRAMITES=ID_INMUEBLES 
	WHERE EXPEDIENTE IN (SELECT ID FROM EXPEDIENTES WHERE ID=V.EXPEDIENTE AND EMBARGO='X')

ALTER TABLE BITACORAS ADD EMBARGO CHAR(1) CHECK(EMBARGO IN ('1','3','4','8','X'))
ALTER TABLE BITACORAS ADD IDEMBARGO INTEGER;
-- DROP CONSTRAINT DE BITACORAS PARA EL MOTIVO
ALTER TABLE BITACORAS ADD CONSTRAINT BITAMOTIVO CHECK(MOTIVO IN('IN','BA','AC','DE','SU','EM'))

CREATE INDEX EXPEDIENTESLOTE3
ON EXPEDIENTES(LOTE_3) TABLESPACE INDICES;

CREATE INDEX EXPEDIENTESLOTE4
ON EXPEDIENTES(LOTE_4) TABLESPACE INDICES;

CREATE INDEX EXPEDIENTESLOTE8
ON EXPEDIENTES(LOTE_8) TABLESPACE INDICES;

CREATE INDEX EXPEDIENTESEMBARGO1
ON EXPEDIENTES(EMBARGO_1) TABLESPACE INDICES;

CREATE INDEX EXPEDIENTESEMBARGO3
ON EXPEDIENTES(EMBARGO_3) TABLESPACE INDICES;

CREATE INDEX EXPEDIENTESEMBARGO4
ON EXPEDIENTES(EMBARGO_4) TABLESPACE INDICES;

CREATE INDEX EXPEDIENTESEMBARGO8
ON EXPEDIENTES(EMBARGO_8) TABLESPACE INDICES;

CREATE INDEX EXPEDIENTESEMBARGOX
ON EXPEDIENTES(EMBARGO_X) TABLESPACE INDICES;

CREATE OR REPLACE VIEW NEXT_RELA_INMUEBLES AS
	SELECT E.ID,E.EXPEDIENTE,E.ZONA,E.DEUDOR,
	E.EMBARGO_4,E.F_EMBARGO_INMUEBLES,C.NOMBRE,E.LOTE_4
	FROM EXPEDIENTES E, CONTRIBUYENTES C
	WHERE E.DEUDOR=C.NIF AND E.EMBARGO_4='P'
	AND E.F_ANULACION IS NULL
	AND E.F_INGRESO IS NULL
	AND E.F_SUSPENSION IS NULL;

CREATE OR REPLACE VIEW INMUEBLES_SUSPENDIDOS AS
	SELECT E.ID,E.EXPEDIENTE,E.AYTO,E.ZONA,E.DEUDOR,
	E.EMBARGO_4,E.F_EMBARGO_INMUEBLES,C.NOMBRE,E.LOTE_4
	FROM EXPEDIENTES E, CONTRIBUYENTES C
	WHERE E.DEUDOR=C.NIF AND E.EMBARGO_4='S'
	AND E.F_INGRESO IS NULL AND E.F_ANULACION IS NULL;
   
CREATE OR REPLACE VIEW vwEmbargoInmueble AS select
	E.ID,E.IDEXPE,E.EN_OTROTRAMITE,E.EXPEDIENTE,E.USUARIO,E.ZONA,
    E.AYTO,E.NIF,DEUDA_TOTAL,OLD_TOTAL,PRINCIPAL,RECARGO,COSTAS,
    INTERESES,IMPORTE_EMBARGADO,P.LOTE_4,P.ESTA_EMBARGO,
    E.QUITAR_EMBARGO,E.F_DILIGENCIA,E.EMITIDA_NOTI,E.NOTI_EMBARGO,
    E.MANDAMIENTO_REGIS,E.F_MANDAMIENTO,E.VALORACION,
    E.REQUERIMIENTO_TITULOS,E.CERTIFICACION_CARGAS,E.FECHA_APERTURA,
    E.N_TERCEROS,E.F_AUTORIZACION,E.F_SUBASTA,E.EMI_NOTI_SUBA,
    E.NOTI_SUBASTA,E.PASO,E.ID_ACUMULA,E.F_ANTERIOR_ACU,
    E.F_ACUMULACION,E.N_RECIBOS,E.AFECTADO,E.HECHO_IMPONIBLE,
    E.P_NOTARIO_ESCR_INS,E.F_P_NOTARIO_ESCR_INS,E.R_NOTARIO_ESCR_INS,
    E.F_R_NOTARIO_ESCR_INS,
	C.NOMBRE,C.CODIGO_POSTAL,C.POBLACION,C.PROVINCIA,C.ESTADO_CIVIL,
    C.VIA ||' ' || C.CALLE ||' ' || C.NUMERO ||' '|| C.ESCALERA ||' '||
    C.PLANTA ||' ' || C.PISO AS DOMICILIO, M.TIPO_CLI, M.NOMBRE AS NOMAYTO
	FROM EMBARGOS_Inmuebles E,CONTRIBUYENTES C, MUNICIPIOS M, EXPEDIENTES P
    WHERE E.NIF=C.NIF AND E.AYTO=M.AYTO AND E.IDEXPE=P.ID;
CREATE OR REPLACE VIEW vwEmbargoSalarioDeudor AS
	SELECT E.ID,E.IDEXPE,E.NIF,E.F_DILIGENCIA,E.DEUDA_TOTAL,
    E.EXPEDIENTE,E.ZONA,E.USUARIO,E.PAGADO,E.LAST_RETENCION, E.LEVANTADO,E.NOTIFICADO,
    E.EMITIDA_EMPRESA,E.EMITIDA_DEUDOR,C.NOMBRE,C.CODIGO_POSTAL,C.POBLACION,C.PROVINCIA,
    C.VIA ||' ' || C.CALLE ||' ' || C.NUMERO ||' '|| C.ESCALERA ||' '||
    C.PLANTA ||' ' || C.PISO AS DOMICILIO, P.LOTE_3, P.AYTO
    FROM EMBARGOS_SALARIOS E,CONTRIBUYENTES C, EXPEDIENTES P
    WHERE E.NIF=C.NIF AND E.IDEXPE=P.ID;
     
CREATE OR REPLACE VIEW NEXT_RELA_SALARIOS AS
	SELECT E.ID,E.EXPEDIENTE,E.ZONA,E.DEUDOR,
	E.EMBARGO_3,E.F_EMBARGO_SALARIOS,C.NOMBRE,E.LOTE_3,E.E_LOTE3
	FROM EXPEDIENTES E, CONTRIBUYENTES C
	WHERE E.DEUDOR=C.NIF AND E.EMBARGO_3='P'
	AND E.F_ANULACION IS NULL
	AND E.F_INGRESO IS NULL
	AND E.F_SUSPENSION IS NULL;
CREATE OR REPLACE VIEW SALARIOS_SUSPENDIDOS AS
	SELECT E.ID,E.AYTO,E.EXPEDIENTE,E.ZONA,E.DEUDOR,
	 E.EMBARGO_3,E.F_EMBARGO_SALARIOS,C.NOMBRE,E.LOTE_3,E.E_LOTE3
	FROM EXPEDIENTES E, CONTRIBUYENTES C
	WHERE E.DEUDOR=C.NIF AND E.EMBARGO_3='S'
	AND E.F_INGRESO IS NULL AND E.F_ANULACION IS NULL;

CREATE OR REPLACE VIEW NEXT_LEVANTA_SALARIOS AS
	SELECT E.ID,E.EXPEDIENTE,E.AYTO,E.ZONA,E.DEUDOR,
	E.EMBARGO_3,E.F_EMBARGO_SALARIOS,C.NOMBRE
	FROM EXPEDIENTES E, CONTRIBUYENTES C
	WHERE E.DEUDOR=C.NIF AND EMBARGO_3='L';
CREATE OR REPLACE VIEW NEXT_RELA_AUTOS AS
	SELECT E.ID,E.EXPEDIENTE,E.ZONA,E.DEUDOR,
	E.EMBARGO_8,E.F_EMBARGO_VEHICULOS,E.LOTE_8,C.NOMBRE
	FROM EXPEDIENTES E, CONTRIBUYENTES C
	WHERE E.DEUDOR=C.NIF AND E.EMBARGO_8='P'
	AND E.F_ANULACION IS NULL
	AND E.F_INGRESO IS NULL
	AND E.F_SUSPENSION IS NULL;
CREATE OR REPLACE VIEW AUTOS_SUSPENDIDOS AS
	SELECT E.ID,E.EXPEDIENTE,E.ZONA,E.AYTO,E.DEUDOR,
	E.EMBARGO_8,E.F_EMBARGO_VEHICULOS,E.LOTE_8,C.NOMBRE
	FROM EXPEDIENTES E, CONTRIBUYENTES C
	WHERE E.DEUDOR=C.NIF AND E.EMBARGO_8='S'
	AND E.F_INGRESO IS NULL AND E.F_ANULACION IS NULL;
CREATE OR REPLACE VIEW NEXT_RELA_CUENTAS AS
	SELECT E.ID,E.EXPEDIENTE,E.ZONA,E.DEUDOR,
 	E.EMBARGO_1,E.F_EMBARGO_CUENTAS,C.NOMBRE
	FROM EXPEDIENTES E, CONTRIBUYENTES C
	WHERE E.DEUDOR=C.NIF AND E.EMBARGO_1='P'
	AND F_INGRESO IS NULL AND F_ANULACION IS NULL
	AND F_SUSPENSION IS NULL;
CREATE OR REPLACE VIEW vwEmbargoVehi AS select
	E.ID,	E.ZONA,E.IDEXPE,E.EXPEDIENTE,E.USUARIO,E.AYTO,E.NIF,P.LOTE_8,P.ESTA_EMBARGO,
	E.QUITAR_EMBARGO, E.F_DILIGENCIA,E.EMITIDA_NOTI,E.NOTI_EMBARGO,
	E.MANDAMIENTO_REGIS,E.F_MANDAMIENTO,E.VALORACION,E.F_SUPLIR_TITULOS,
	DEUDA_TOTAL, COSTAS, INTERESES, IMPORTE_EMBARGADO,
	IMPORTE_a_embargar, IMPORTE_CARGAS,
	E.REQUERIMIENTO_TITULOS,E.CERTIFICACION_CARGAS,
	E.EMITIDA_CARGAS,E.FECHA_APERTURA,E.N_TERCEROS,E.F_AUTORIZACION,E.F_SUBASTA,
	E.EMI_NOTI_SUBA,E.NOTI_SUBASTA,E.PASO,
	C.NOMBRE,C.CODIGO_POSTAL,C.POBLACION,C.PROVINCIA,C.ESTADO_CIVIL,
    C.VIA ||' ' || C.CALLE ||' ' || C.NUMERO ||' '|| C.ESCALERA ||' '||
    C.PLANTA ||' ' || C.PISO AS DOMICILIO, M.TIPO_CLI, M.NOMBRE AS NOMAYTO
	FROM EMBARGOS_AUTOS E, EXPEDIENTES P, CONTRIBUYENTES C, MUNICIPIOS M
    WHERE E.IDEXPE=P.ID AND E.NIF=C.NIF AND E.AYTO=M.AYTO;
CREATE OR REPLACE VIEW CUENTAS_SUSPENDIDAS AS
	SELECT E.ID,E.EXPEDIENTE,E.ZONA,E.AYTO,E.DEUDOR,
	E.EMBARGO_1,E.F_EMBARGO_CUENTAS,C.NOMBRE
	FROM EXPEDIENTES E, CONTRIBUYENTES C
	WHERE E.DEUDOR=C.NIF AND E.EMBARGO_1='S'
	AND E.F_INGRESO IS NULL AND E.F_ANULACION IS NULL;
CREATE OR REPLACE VIEW NEXT_RELA_OTROS AS
	SELECT E.ID,E.EXPEDIENTE,E.ZONA,E.DEUDOR,
    E.EMBARGO_X,E.F_EMBARGO_OTROS,C.NOMBRE
	FROM EXPEDIENTES E, CONTRIBUYENTES C
	WHERE E.DEUDOR=C.NIF AND E.EMBARGO_X='P'
	AND F_INGRESO IS NULL AND F_ANULACION IS NULL
	AND F_SUSPENSION IS NULL;
CREATE OR REPLACE VIEW OTROS_SUSPENDIDOS AS
	SELECT E.ID,E.EXPEDIENTE,E.AYTO,E.ZONA,E.DEUDOR,
    E.EMBARGO_X,E.F_EMBARGO_OTROS,C.NOMBRE
	FROM EXPEDIENTES E, CONTRIBUYENTES C
	WHERE E.DEUDOR=C.NIF AND E.EMBARGO_X='S'
	AND F_INGRESO IS NULL AND F_ANULACION IS NULL;
CREATE OR REPLACE VIEW IMPORTE_VALORES AS
SELECT ID,PADRON,YEAR,PERIODO,RECIBO,TIPO_DE_OBJETO,
	 AYTO,NIF,NOMBRE,CLAVE_CONCEPTO,COTITULARES,
	 EXPEDIENTE,F_IN_EXPEDIENTE,ID_INMUEBLES,ID_SALARIOS,ID_VEHICULOS,
	 EN_INMUEBLES,L_EMBARGO,
	 PROPU_INSOLVENTE,RELACION_APREMIO,ORDEN_APREMIO,
	 NOTIFICADO,F_NOTIFICACION,F_INGRESO,COD_INGRESO,
	 FECHA_DE_BAJA,CODIGO_DE_BAJA,F_SUSPENSION,FECHA_PROPUESTA_BAJA,
	 CODIGO_OPERACION,NUMERO_OPERACION,IS_LIVE,
	 VOL_EJE,ESTADO_BANCO,COD_DEVUELTO_BANCO,
	 F_CARGO,N_CARGO,YEAR_CONTRAIDO,
	 FIN_PE_VOL,F_APREMIO,
	 CERT_DESCUBIERTO,SELECCION,TIPO_DE_TRIBUTO,
	 DOM_TRIBUTARIO,OBJETO_TRIBUTARIO,
	 CUOTA_INICIAL, DEMORA_PENDIENTE, ENTREGAS_A_CUENTA,
	 PRINCIPAL, RECARGO, COSTAS, DEMORA, RECARGO_O_E,
	 PRINCIPAL + RECARGO + COSTAS + DEMORA + DEMORA_PENDIENTE AS IMPORTE,
	 PRINCIPAL + RECARGO + COSTAS + DEMORA -
             ENTREGAS_A_CUENTA + DEMORA_PENDIENTE AS PENDIENTE
FROM VALORES;

DROP TRIGGER T_NoSalaEmpresas

001_TRIGGERS.sql                  : ok, sin modificaciones.
005_TRIGGERS_VALORES.SQL          : cambiado
007_SEGURIDAD_Y_ACCESOS.SQL       : ok, sin modificaciones.
008_PAQUETE_SEGUIMIENTO.SQL       : ok, sin modificaciones.
010_CAJA.SQL                      : ok, sin modificaciones.
020_PUNTEO.sql                    : ok, sin modificaciones.
030_OTROS.sql                     : cambiado

068_PAQUETE_DEMORA.SQL            : ok, sin modificaciones.
070_LIQUI_DEMORA.SQL              : ok, sin modificaciones.
070_DEMORA.SQL                     hay que modificarlo

109_EXPEDIENTES_ACUMULACION.SQL   : ok, sin modificaciones. ¿INUTIL?
110_EXPEDIENTES_GESTION.SQL       hay que modificarlo
111_EXPEDIENTES_PAQUETE_CREAR.sql : ok, sin modificaciones.
111_PAQUETE_VALORES_VARIOS.sql    : ok, sin modificaciones.
112_EXPEDIENTES_CREAR.SQL         : cambiado, y hay que revisarlo 
113_EXPEDIENTES_ENTREGAS.SQL      hay que modificarlo 
114_EXPEDIENTES_TRIGGERS.SQL      : cambiado, y hay que hacer modificaciones en PAGA_EXPEDIENTE
115_EXPEDIENTES_INFORMES.SQL      hay que modificarlo
130_TRAMITES.SQL                  : cambiado
140_NOTIFICA.SQL                  hay que modificarlo
140_NOTIFICA_PAQUETE.SQL          hay que modificarlo
141_TRIGGER_NOTIFICACIONES.SQL    hay que modificarlo
150_SALARIOS.SQL                  : cambiado
159_NEWCUENTAS.SQL                : cambiado
160_CUENTAS.sql                   : cambiado
161_CUENTAS_TRIGGERS.SQL          : ok, sin modificaciones.
170_VEHICULOS.SQL                 : cambiado
180_INMUEBLES.SQL                 : cambiado

INTERES_DILIGENCIA??

150: INTERES_DILIGENCIA??
     PUT_UnExpeEnLoteSalarios, ver que valores entran en el embargo (suspendidos?) y el importe de dónde lo toma
     
     acumulaciones/aminoraciones

180: Quito_ExpeLoteInmuebles
     BORRA_LEVANTA_INMU
     INMUEBLESAFECTOS
     
   